# 12. 프로미스 개념부터 활용까지 JavaScript Promise

## Promise <a href="#promise" id="promise"></a>

* JavaScript에서 제공되는 비동기를 간단하게 처리할 수 있는 Object
* 콜백함수 대신 사용할 수 있다.
* Promise 안에서는 무거운 일을 수행하게 된다.
  * 네트워크에서 데이터를 받아오거나 파일에서 큰 데이터를 읽는 과정을 수행하는 것을 동기적으로 처리하면, 다음 코드가 실행되지 않으므로 비동기 처리를 하는 것이 좋다.
* state
  * 상태
  * process가 동작을 수행중인지, 완료되어서 성공 또는 실패했는지
* producer / consumer
  * 정보 제공자 / 소비자



```javascript
1. state 상태
pending -> fulfilled or rejected
- pending: operation을 수행 중 상태
- fulfilled: operation을 완료하고 성공한 상태
- rejected: operation을 완료했지만 실패한 상태

2. Producer = class
- new키워드로 Promise()객체 생성
- executor : Promise의 생성자인 콜백함수, 하위에 두개의 콜백함수를 가지고 있다.
	- resolve: 기능이 정상적으로 수행되었을 때 데이터를 전달하는 콜백함수
	- reject: 기능을 수행하다가 문제 발생시 호출되는 콜백함수

const promise = new Promise((resolve, reject) => {
  // doing some heavy work(network에서 데이터 받아오기, read files)
  console.log('doing something...');
  
  // New Promise를 만드는 순간 executor가 바로 실행!!!!!!!!!!!!
  // 네트워크 통신코드를 넣어 놓았다면, Promise가 만들어지는 순간 통신을 수행
  // 불필요한 통신을 할 수 있으므로 주의
  
  setTimeout(() => {
    resolve('ellie');
  }, 2000);
});

3. Consumers(then catch finally)
then, catch, finally를 이용해서 값을 받아올 수 있다.
chaining을 할 수 있다.

1) then
- promise가 정상적으로 잘 수행이되었을 때
- 값을 전달하거나 promise를 전달
- 같은 promise를 return

const promise = new Promise((resolve, reject) => {
  // doing some heavy work(network, read files)
  console.log('doing something...');
  setTimeout(() => {
    resolve('siru');
  }, 2000);
});

promise.then((value) => {
  console.log(value);
});

2) catch
- promise가 수행중에 Error 발생했을 때
- Error: JavaScript에서 제공하는 obejct

const promise = new Promise((resolve, reject) => {
  // doing some heavy work(network, read files)
  console.log('doing something...');
  setTimeout(() => {
    reject(new Error('no network'));
  }, 2000);
});

promise
.then((value) => {
  console.log(value);
})
.cath(error => {
  consoel.log(error);
});

3) finally: 최근 추가!
- 성공, 실패와 관계없이 무조건 마지막에 호출

const promise = new Promise((resolve, reject) => {
  // doing some heavy work(network, read files)
  console.log('doing something...');
  setTimeout(() => {
    reject(new Error('no network'));
  }, 2000);
});

promise
.then((value) => {
  console.log(value);
})
.cath(error => {
  consoel.log(error);
})
.finally(() => {
  console.log('finally');
});

4. Promise chaining
const fetchNumber = new Promise((resolve, reject) => {
  setTimeout(() => resolve(1), 1000);
});

fetchNumber
.then(num => num * 2)
.then(num -> num * 3)
.then(num => {
  return new Promise((resolve, reject) => {
    setTimeout((() => resolve(num - 1), 1000));
  });
})
.then(num => console.log(num));
// then은 값이나 promise를 전달할 수 있음

5. 오류 처리
const getHen = () =>
    new Promise((resolve, reject) => {
    setTimeout(() => resolve('🐓'), 1000);
  });
const getEgg = hen =>
    new Promise((resolve, reject) => {
    setTimeout(() => reject(new Error(`error! ${hen} => 🥚`)), 1000);
  });
const cook = egg =>
    new Promise((resolve, reject) => {
    setTimeout(() => resolve(`${egg} => 🍳`), 1000);
  });

getHen()
	// 전달시 받아오는 값을 다른 함수로 바로 하나를 호출하면 생략가능
    .then(hen => getEgg(hen)) // → .then(getEgg) 
    .then(Egg => cook(egg))  // → .then(cook) 
    .then(meal => console.log(meal)); //→ .then(consloe.log); 

// getEgg에서 오류가 발생해도 적절한 처리를 할 수 있다.
getHen()
    .then(getEgg)
    .catch(error => {
    	return '🥖';
    })
    .then(cook)
    .then(console.log)
    .catch(console.log);
    
6. 콜백함수 개선
const userStorage = new UserStorage();
const id = prompt('enter your id');
const password = prompt('enter toru password');

class UserStorage {
  loginUser(id, password) {
    return new Promise((resolve, reject) => {
            setTimeout(() => {
        if (
          (id === 'jiyun' && password === '1234') ||
          (id === 'ellie' && password === '0000')
        ) {
          resolve(id);
        } else {
          reject(new Error('not found'));
        }
      }, 2000);
    });
  }
  getRoles(user) {
    return new Promise((resolve, reject) => {
            setTimeout(() => {
        if (user === 'eliie') {
          resolve({ name: 'jeliiem', role: 'admin' });
        } else {
          reject(new Error('no access'));
        }
      }, 1000);
    });
  }
}

userStorage
.loginUser(id, password)
.then(userStorage.getRoles)
.then(user => alert( `Hello ${user.name}, you have a ${user.role}`))
.catch(console.log);
```
